//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by simpledivx.rc
//
#define IDS_ABOUTBOX                    1
#define IDD_SimpleDivX_DIALOG           102
#define IDI_NET                         128
#define IDD_DIALOG_INPUTFILES           129
#define IDD_DIALOG_AUDIO_OPTIONS        132
#define IDD_DIALOG_VIDEO_OPTIONS        133
#define IDD_ABOUTBOX                    135
#define IDD_DIALOG_COMPRESSION          139
#define IDD_DIALOG_OUTPUTFILES          140
#define IDD_DIALOG1                     141
#define IDD_DIALOG_CODEC_OPTIONS        143
#define IDI_ICON_LOGFILE                150
#define IDB_BITMAP_ENDCREDITS           151
#define IDB_KEYS                        154
#define IDB_CALC                        155
#define IDB_DVDICON                     156
#define IDB_DVDDRIVE                    157
#define IDB_FOLDERPROG                  158
#define IDB_GEARS2                      160
#define IDB_GLOBE                       161
#define IDB_GLOBE1                      162
#define IDB_INFO                        163
#define IDB_INFO2                       164
#define IDB_KEY                         165
#define IDB_BITMAP13                    166
#define IDB_ARROW                       167
#define IDB_NOTE2                       168
#define IDB_PIECE                       169
#define IDB_PLUSAUDIO                   170
#define IDB_RESIZE                      171
#define IDB_SUB                         172
#define IDI_TOOLS                       175
#define IDI_VOLUME                      178
#define IDI_CALC                        179
#define IDI_DVDDRIVE                    180
#define IDI_DVDICON                     181
#define IDI_FILM                        182
#define IDI_FOLDER1                     183
#define IDI_GEAR                        184
#define IDI_INFO                        188
#define IDI_INFO1                       189
#define IDI_MAPFOLDER                   190
#define IDI_NOTE                        191
#define IDI_RESIZE                      193
#define IDI_SPEAKER                     195
#define IDI_SUNSET                      196
#define IDI_AUDIOVIDEO                  197
#define IDI_TIME                        199
#define IDI_PIECE                       200
#define IDI_MPG                         203
#define IDI_GEARS3                      206
#define IDI_KEY1                        208
#define IDI_SPK2                        209
#define IDB_BITMAP1                     221
#define IDD_DIALOG_ADV                  223
#define IDD_DIALOG_SETUP                224
#define IDI_NOTEPAD2                    225
#define IDI_DIVX                        226
#define IDI_WORLDSOUND                  230
#define IDI_PROC                        231
#define IDI_AUDIO                       232
#define IDI_NOTEPAD                     234
#define IDD_DIALOG_VIDEO_ADV            235
#define IDD_DIALOG_PROJECT              237
#define IDI_LANGSEL                     238
#define IDI_SUBTITLES                   242
#define IDD_DIALOG_MISC                 243
#define IDC_MENCODER_LOCATION           1000
#define IDC_MENCODER_EDIT               1001
#define IDC_VIDEOPREVIEW                1004
#define IDC_VIRTUALDUB_EDIT             1005
#define IDC_VOBFOLDER                   1006
#define IDC_MKVMERGE_EDIT               1006
#define IDC_FOLDER_EDIT                 1007
#define IDC_STATIC_VBRTXT               1007
#define IDC_STATIC_CBRTXT               1008
#define IDC_RADIO20                     1009
#define IDC_VIRTUALDUB_LOCATION         1009
#define IDC_RADIO21                     1010
#define IDC_MKVMERGE_LOCATION           1010
#define IDC_CHECK_FRAMERANGE            1011
#define IDC_INFO                        1011
#define IDC_START_FRAME                 1012
#define IDC_START                       1012
#define IDC_END_FRAME                   1013
#define IDC_CREATE_AUDIO                1013
#define IDC_COMBO_FPS                   1014
#define IDC_COMBO_DEINTERLACE           1015
#define IDC_COMBO_POSTFILTER            1016
#define IDC_COMBO_REFQ                  1017
#define IDC_COMBO_OUTPUTMODE            1018
#define IDC_STATIC_FINAL                1018
#define IDC_COMBO_OUTPUTFORMAT          1019
#define IDC_EDIT_CX                     1020
#define IDC_PROGRESS                    1020
#define IDC_EDIT_CY                     1021
#define IDC_EDIT_DX                     1023
#define IDC_SLIDER_SPLIT                1023
#define IDC_EDIT_DY                     1024
#define IDC_CHECK_SPLIT                 1024
#define IDC_AVI_LOCATION                1025
#define IDC_TEMP_LOCATION               1026
#define IDC_OUTPUTAVIFOLDER             1027
#define IDC_TEMPFOLDER                  1028
#define IDC_STATIC_SPLIT                1029
#define IDC_SPLITAT                     1029
#define IDC_PROJNAME                    1030
#define IDC_COMBO_AUDIO_STREAMID        1031
#define IDC_MPLAYER_EDIT                1031
#define IDC_COMBO_SIZE                  1031
#define IDC_STATIC_DIVX_OPTIONS         1032
#define IDC_CHECK_OVERWRITE_AVI         1033
#define IDC_RADIO_DIVX1                 1033
#define IDC_RADIO_DIVX2                 1034
#define IDC_RADIO_DIVX3                 1035
#define IDC_RADIO_DIVX4                 1036
#define IDC_GET_TIME                    1038
#define IDC_MAXBITRATE                  1040
#define IDC_MPLAYER_LOCATION            1040
#define IDC_MINBITRATE                  1041
#define IDC_EC_BR                       1042
#define IDC_BROWSE_PROGRAM              1043
#define IDC_STATIC_LANG                 1043
#define IDC_EDIT_PROGRAM_LOCATIONS      1044
#define IDC_STATIC_RATIO                1045
#define IDC_GET_DEF                     1045
#define IDC_STATIC_VIDEO_INFORMATION    1047
#define IDC_CHECK_NORM                  1048
#define IDC_EDIT_HOUR                   1051
#define IDC_EDIT_MIN                    1052
#define IDC_EDIT_SEC                    1053
#define IDC_EDIT_FRAMES                 1054
#define IDC_EDIT_FileSize               1055
#define IDC_EDIT_KEYFRAME               1056
#define IDC_EDIT_SMOOTH                 1058
#define IDC_CHECK_NORM2                 1059
#define IDC_EDIT_ENDCREDITS_FRAMES      1059
#define IDC_CHECK_SHUTDOWN              1060
#define IDC_CHECK_LBA                   1063
#define IDC_STATIC_KBPS                 1063
#define IDC_STATIC_RECOMPRESS_PCT       1063
#define IDC_EDIT_LBA                    1064
#define IDC_STATIC_Q                    1064
#define IDC_CHECK_WAVEUP                1065
#define IDC_CHECK_MAIN                  1065
#define IDC_STATIC_CHECK_MAIN           1065
#define IDC_CHECK_ALL                   1066
#define IDC_STATIC_CHECK_ALL            1066
#define IDC_EDIT_CREDITS                1070
#define IDC_CHECK_VIDEO                 1071
#define IDC_EDIT_DIVXLOG                1073
#define IDC_COMBO_AUDIO                 1074
#define IDC_CHECK_EXTRACT_ALL_AUDIO     1075
#define IDC_STATIC_LENGTH               1077
#define IDC_RADIO_MP3                   1078
#define IDC_RADIO_AC3                   1079
#define IDC_CHECK_CONVERT_ALL_AUDIO     1080
#define IDC_RADIO1                      1081
#define IDC_RADIO2                      1082
#define IDC_RADIO_AUTO                  1085
#define IDC_RADIO_MANUAL                1086
#define IDC_RADIO_END1                  1089
#define IDC_RADIO_END3                  1090
#define IDC_RADIO_END2                  1091
#define IDC_RADIO_FAST                  1097
#define IDC_CHECK_AUDIO                 1099
#define IDC_RADIO_NORMAL                1099
#define IDC_STATIC_RESOLUTION           1100
#define IDC_PASS_0                      1100
#define IDC_STATIC_FPS                  1101
#define IDC_PASS_1                      1101
#define IDC_STATIC_FORMAT               1102
#define IDC_PASS_2                      1102
#define IDC_STATIC_CHAPTERS             1103
#define IDC_RADIO_OGG                   1104
#define IDC_RADIO_3                     1110
#define IDC_RADIO_4                     1111
#define IDC_RADIO_5                     1112
#define IDC_RADIO_6                     1113
#define IDC_CHECK_GMC                   1114
#define IDC_LIST1                       1115
#define IDC_LIST_LANG                   1115
#define IDC_STATIC_CONV                 1116
#define IDC_STATIC_AUDIOSTRID           1117
#define IDC_STATIC_AUDIOLANG            1118
#define IDC_STATIC_AC3KBPS              1120
#define IDC_STATIC_AC3CHAN              1121
#define IDC_STATIC_AUDKBPS              1122
#define IDC_LOGFILE                     1124
#define IDC_STATIC_STAR                 1125
#define IDC_ADV_SET                     1125
#define IDC_CHECK_QP                    1126
#define IDC_CHECK_BI                    1127
#define IDC_STATIC_PRO                  1132
#define IDC_STATIC_5                    1133
#define IDC_STATIC_NORMAL               1133
#define IDC_STATIC_MINQ                 1134
#define IDC_STATIC_MAXQ                 1135
#define IDC_EDIT_MINQ                   1141
#define IDC_EDIT_MAXQ                   1142
#define IDC_STATIC_FRAMES               1142
#define IDC_STATIC_FRAMES_CPAGE         1142
#define IDC_STATUS                      1143
#define IDC_STATIC_TITLES               1144
#define IDC_RADIO_AUTO_LOGFILENAMING    1147
#define IDC_RADIO_MANUAL_LOGFILENAMING  1148
#define IDC_CHECK_AUTO                  1152
#define IDC_EDIT_AC3_PRELOAD            1153
#define IDC_EDIT_AC3_FRAMES             1154
#define IDC_CHECK_DEL_TEMP              1156
#define IDC_VIDEO_PRIO                  1157
#define IDC_AUDIO_PRIO                  1158
#define IDC_CHECK_DEINTER               1158
#define IDC_DISK_PRIO                   1159
#define IDC_CHECK_VHQ                   1159
#define IDC_HOMEPAGE                    1160
#define IDC_LST_LANGUAGES               1160
#define IDC_EMAIL                       1161
#define IDC_SPIN_AMPLIFY                1163
#define IDC_EDIT_AMPLIFY                1165
#define IDC_RADIO_NORECOMPRESSAC3       1170
#define IDC_RADIO_RECOMPRESSAC3         1171
#define IDC_STATIC_OGG_CHANNELS         1172
#define IDC_STATIC_MP3_CHANNELS         1173
#define IDC_BUTTON_ADV                  1174
#define IDC_BUTTON_ADVANCED             1174
#define IDC_RADIO_PANSCAN               1175
#define IDC_LIST_BATCH                  1177
#define IDC_ADD                         1178
#define IDC_REMOVE                      1179
#define IDC_BUTTON_PRINTDEBUG           1180
#define IDC_BUTTON_UP                   1181
#define IDC_BUTTON_DOWN                 1182
#define IDC_RADIO_NORMALMODE            1183
#define IDC_RADIO_BATCHMODE             1184
#define IDC_BUTTON_CLEAR                1185
#define IDC_CHECK_VBR                   1186
#define IDC_BUTTON_MODIFY               1186
#define IDC_STATIC_DELAY                1187
#define IDC_CHECK1                      1188
#define IDC_CHECK_DELETE_BATCH          1188
#define IDC_CHECK_LUMI                  1188
#define IDC_CHECK_ALL_LANG              1188
#define IDC_STATIC_INPUT_FILES          1190
#define IDC_STATIC_PRIORITY_SETTINGS    1191
#define IDC_STATIC_ADVANCED_AUDIO_SETTINGS 1192
#define IDC_STATIC_EXTERNAL_PROGRAMS    1193
#define IDC_STATIC_LANGUAGE_SETTINGS    1194
#define IDC_STATIC_LANGUAGE             1195
#define IDC_STATIC_VOB_FILES            1196
#define IDC_STATIC_RES                  1197
#define IDC_STATIC_FRAMERATE            1198
#define IDC_STATIC_MOVIE_LENGTH         1199
#define IDC_STATIC_ASPECT               1200
#define IDC_STATIC_VF                   1201
#define IDC_STATIC_FOLDER               1202
#define IDC_STATIC_FRAMES_PER_SECOND    1203
#define IDC_STATIC_CHAP                 1203
#define IDC_STATIC_SOURCE_FORMAT        1204
#define IDC_STATIC_W1                   1205
#define IDC_STATIC_W2                   1206
#define IDC_STATIC_W3                   1207
#define IDC_STATIC_H1                   1208
#define IDC_STATIC_H2                   1209
#define IDC_STATIC_CROPPING             1210
#define IDC_STATIC_RESIZING             1211
#define IDC_STATIC_CUSTOM_OUTPUT_FORMAT 1212
#define IDC_STATIC_VIDEO_OPTIONS        1213
#define IDC_STATIC_FRAME_OPTIONS        1214
#define IDC_STATIC_TO                   1215
#define IDC_STATIC_GENERAL_AUDIO        1216
#define IDC_STATIC_AUDIO_STREAMS_LANGUAGES 1217
#define IDC_STATIC_AUDIO_FORMAT         1218
#define IDC_STATIC_AUDIO_BITRATE_AND_CONVERSION 1219
#define IDC_STATIC_AUDIO_KBPS           1220
#define IDC_STATIC_CODEC_OPTIONS        1221
#define IDC_STATIC_CHOOSE_CODEC         1222
#define IDC_STATIC_MAX_KF               1223
#define IDC_STATIC_FIRST_PASS_LOCATION  1224
#define IDC_STATIC_PASS_OPTIONS         1225
#define IDC_STATIC_BITRATE_FILE_OPTIONS 1226
#define IDC_STATIC_ADV_BITRATE          1227
#define IDC_STATIC_END_CREDITS_OPTIONS  1228
#define IDC_STATIC_MOVIE_LENGTH_CPAGE   1230
#define IDC_STATIC_FILESIZE             1231
#define IDC_STATIC_VIDEO_BITRATE        1232
#define IDC_STATIC_DESCRIPTION          1233
#define IDC_STATIC_HOURS                1234
#define IDC_STATIC_MINUTES              1235
#define IDC_STATIC_SECONDS              1236
#define IDC_STATIC_FRAMES_CPAGE2        1237
#define IDC_STATIC_PROJECT_OPTIONS      1238
#define IDC_STATIC_BATCH_SETTINGS       1239
#define IDC_STATIC_PROJECT_NAME         1240
#define IDC_STATIC_TEMP_FOLDER          1241
#define IDC_STATIC_OUTPUT_FOLDER        1242
#define IDC_STATIC_SYSTEM_SETTINGS      1243
#define IDC_STATIC_STATUS_INFORMATION   1244
#define IDC_STATIC_PROGRESS             1245
#define IDC_STATIC_AC3_PRELOAD_VALUE    1246
#define IDC_STATIC_AC3_INTERLEAVE_VALUE 1247
#define IDC_STATIC_SETUP_FRAMES         1248
#define IDC_STATIC_AUDIO_PRIORITY       1249
#define IDC_STATIC_VIDEO_PRIORITY       1250
#define IDC_STATIC_DISK_PRIORITY        1251
#define IDC_STATIC_SETTING_WARNING      1252
#define IDC_STATIC_PROGRAM_LOCATIONS    1253
#define IDC_COMBO1                      1256
#define IDC_CMB_SPLIT_PARTS             1256
#define IDC_COMBO_MODE                  1256
#define IDC_COMBO_SOURCE_FORMAT         1256
#define IDC_COMBO_CODEC                 1257
#define IDC_CHECK2                      1258
#define IDC_CHECK_CHROMA                1258
#define IDC_CHECK_SPLIT_FADEOUT         1258
#define IDC_STATIC_GENERAL_SUBTITLE     1259
#define IDC_CREATE_SUBTITLES            1261
#define IDC_STATIC_SUBTITLESTRID        1262
#define IDC_LIST_VOBS                   1264
#define IDC_LIST2                       1265
#define IDC_STATIC_CONTAINER            1266
#define IDC_RADIO_CONTAINER_AVI         1267
#define IDC_RADIO_CONTAINER_MATROSKA    1269
#define IDC_RADIO_CONTAINER_OGM         1270
#define IDC_STATIC_DEINTERLACE          1271
#define IDC_RADIO_CONTAINER_MP4         1271
#define IDC_STATIC_SPLIT_IN_PARTS       1272
#define IDC_STATIC_SPLIT_MB             1273
#define IDC_CHECK_DARK                  1274
#define IDC_CHECK3                      1275
#define IDC_CHECK_TRELLIS               1275
#define IDC_COMBO_TITLES                1276
#define IDC_STATIC_VIDEO_AND_AUDIO      1277
#define IDM_ABOUTBOX                    4090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        247
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1278
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
